version: '3.8'

services:
  web:
    container_name: PicScape-WEB
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always
    pull_policy: build
    environment:
      VUE_APP_API_URL: ${VUE_APP_API_URL}
    env_file:
      - stack.env
